### ISSUE TITLE
Load app_logo from disk

### ISSUE THREAD

**Issue by hagsted** [arnaudmiribel/streamlit-extras#100]
It would be nice to have an option to use a local file in the project as the app_logo.

It is described how to encode the data for use at stackoverflow: 
https://stackoverflow.com/questions/73251012/put-logo-and-title-above-on-top-of-page-navigation-in-sidebar-of-streamlit-multi

Right now I have used a hack like this:
```
def get_base64_of_bin_file(png_file):
    with open(png_file, "rb") as f:
        data = f.read()
    return base64.b64encode(data).decode()

logo = "data:image/png;base64," + get_base64_of_bin_file("project/data/logo.png")

add_logo(logo)
```

**Comment by arnaudmiribel** [comment]
Hey @hagsted, sorry for taking so long to reply. Pinging @blackary who's the author of that app logo extra, he may have stronger opinions, but since this is net benefit I guess it should not be a problem!
