### ISSUE TITLE
Getting error after importing the required packages

### ISSUE THREAD

**Issue by Sarvoo** [arnaudmiribel/streamlit-extras#104]
gather_metrics() got an unexpected keyword argument 'name'

**Comment by louispk** [comment]
I am also encountering this issue when trying to import switch_page to use for Page switching buttons. Issue persists after package reinstall and across devices, currently installed version is 0.2.4

Thanks for any help in advance!

**Comment by arnaudmiribel** [comment]
Oh wow, hi @louispk I was exactly writing to ask for more details. Can you tell me your Streamlit version as well?

**Comment by arnaudmiribel** [comment]
I tried to reproduce the error but it's all working great for me with `streamlit==1.16.0` and `streamlit-extras==0.2.4`

Code:
```
from importlib.metadata import version

import streamlit as st
from streamlit_extras.switch_page_button import switch_page

st.write("Extras version", version("streamlit-extras"))
st.write("Streamlit version", st.__version__)


if st.button("Click"):
    switch_page("Page 1")
```

**Comment by louispk** [comment]
Thanks for the quick reply. Seems to be my fault as I was still running streamlit 1.13.0 for some reason, updating to 1.16.0 solved it :)
