### ISSUE TITLE
Pip install installs previous version

### ISSUE THREAD

**Issue by fabioannovazzi** [arnaudmiribel/streamlit-extras#106]
Neither pip install non pip upgrade install the new version.

I have la last Verdon of streamlit installéd 1.16

**Comment by arnaudmiribel** [comment]
Hey!

Can you share the output you get when you try:

```
pip install streamlit-extras --upgrade
```

Thanks!

**Comment by fabioannovazzi** [comment]
[image: image.png]

**Comment by arnaudmiribel** [comment]
Hey @fabioannovazzi, the image doesn't show!

**Comment by fabioannovazzi** [comment]
Requirement already up to date bla bla bla..

**Comment by fabioannovazzi** [comment]
---------- Forwarded message ---------
From: Fabio Annovazzi ***@***.***>
Date: Tue, Dec 20, 2022, 07:41
Subject: Re: [arnaudmiribel/streamlit-extras] Pip install installs previous
version (Issue #106)
To: arnaudmiribel/streamlit-extras <
***@***.***>


[image: image.png]

**Comment by arnaudmiribel** [comment]
@fabioannovazzi I'd love to help but I'm lacking a reproducible context here, or at least a description of your settings and tracebacks when using the pip install commands. 

(And your image doesn't show, again)

If what you get is "Requirement already up to date bla bla bla.." then I guess streamlit-extras is already at its latest version, but you might be using a different python environment when running your app.
