### ISSUE TITLE
🐛 [BUG] - https://extras.streamlit.app/ not loading

### ISSUE THREAD

**Issue by andfanilo** [arnaudmiribel/streamlit-extras#127]
### Description

Is it only me? https://extras.streamlit.app/ is not running anymore on different Internet networks, web browsers and laptops :( 

I'm stuck on "Please Wait" with some `GET https://extras.streamlit.app/~/st-allowed-message-origins 404` messages in the web console..

![image](https://user-images.githubusercontent.com/5351877/221586084-24e043d6-5e63-4ddd-80d5-54d6d4e7829c.png)

### Reproduction steps

```bash
Browse to https://extras.streamlit.app/
```

### Screenshots

```bash
![image](https://user-images.githubusercontent.com/5351877/221586084-24e043d6-5e63-4ddd-80d5-54d6d4e7829c.png)
```

### Logs

```bash
GET https://extras.streamlit.app/~/st-allowed-message-origins 404
```

### Version of streamlit

-

### Version of streamlit-extras

-

**Comment by tylerjrichards** [comment]
@andfanilo we also surfaced this internally (by we, I really mean @blackary) to try and ensure community cloud has lower downtime
