### ISSUE TITLE
✨ [IDEA] - Sandbox

### ISSUE THREAD

**Issue by arnaudmiribel** [arnaudmiribel/streamlit-extras#133]
### Description

Just a Python sandbox running on Pyodide (through jupyterlite)

### Minimal code for the extra

https://playground.streamlit.app/?q=pyodide-sandbox

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Rjchauhan18** [comment]
hello @arnaudmiribel 
So, according to this Description do you want to add the new streamlit extra component of jupiterlite just like [this](https://playground.streamlit.app/?q=pyodide-sandbox)

If I have understood the issue correct then please assign this issue to me.

**Comment by arnaudmiribel** [comment]
Hey @Rjchauhan18, that's exactly it! I'm thinking an extra like that would be useful to have viewers able to play with some Python tasks within the app. 

Assigned you 💪

**Comment by Rjchauhan18** [comment]
Hey @arnaudmiribel  
Can you please review it ?
