### ISSUE TITLE
Release the replacement of experimental_memo

### ISSUE THREAD

**Issue by jbvsmo** [arnaudmiribel/streamlit-extras#134]
### Description

I see `experimental_memo` have been replaced with `cache_data` in latest code, but this has not been released yet. 

If that is the case, please do release a new version of this package

### Minimal code for the extra

```python
N/A
```

### Screenshots

```bash
N/A
```

**Comment by arnaudmiribel** [comment]
Hey @jbvsmo, thanks for the reminder! 

Mind trying `pip install streamlit-extras --upgrade`? Just merged and released!

**Comment by jbvsmo** [comment]
@arnaudmiribel Thank you, it works!
