### ISSUE TITLE
Error while opening the main documentation

### ISSUE THREAD

**Issue by data-panda** [arnaudmiribel/streamlit-extras#140]
I am keeping on getting this error while open the mainpage. Tried different browsers and also tried clearing cache.

<img width="627" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/9045578/76a936c6-5b9b-43ff-94a3-f71fbe2ce0eb">

**Comment by Felipe-Scandiuzzi** [comment]
Same around here!

**Comment by BorgPrincess** [comment]
Still no news?

**Comment by arnaudmiribel** [comment]
Hi there! Thanks a ton for flagging this. I'll investigate and fix this asap

**Comment by arnaudmiribel** [comment]
The app's back up! 🥳
