### ISSUE TITLE
Error running app

### ISSUE THREAD

**Issue by BPMData** [arnaudmiribel/streamlit-extras#149]
Tried both Firefox and Microsoft Edge, both bring up a frowning emoji and the following text:

Oh no.
Error running app. If this keeps happening, please [contact support](https://github.com/arnaudmiribel/streamlit-extras/issues/new).

Was working fine yesterday around 7 pm!

**Comment by arnaudmiribel** [comment]
Thanks @BPMData, the app is now up again.
