### ISSUE TITLE
🐛 [BUG] - https://extras.streamlit.app/ is not working

### ISSUE THREAD

**Issue by monipip3** [arnaudmiribel/streamlit-extras#152]
### Description

<img width="606" alt="Screen Shot 2023-07-10 at 4 57 03 PM" src="https://github.com/arnaudmiribel/streamlit-extras/assets/16262065/1958b31b-7c84-40f4-a72b-7ca029c55da3">

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Version of streamlit

1.24.1

### Version of streamlit-extras

0.2.7

**Comment by LimbourgMatthias** [comment]
Seems like it works again but it's terribly slow. An alternative source of documentation should be provided.

**Comment by arnaudmiribel** [comment]
The app is up again. @LimbourgMatthias adding this as an improvement idea
