### ISSUE TITLE
Static documentation for streamlit-extras

### ISSUE THREAD

**Issue by arnaudmiribel** [arnaudmiribel/streamlit-extras#173]

**Comment by andrewssobral** [comment]
Yes, it should be nice to have. 

Each time I need to check its functionalities I need to go through https://extras.streamlit.app/ and sometimes it’s down 😔

<img width="1680" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/483114/4c3b9c71-0409-44b3-be78-2723c9281c6e">
