### ISSUE TITLE
app down

### ISSUE THREAD

**Issue by RichardHruby** [arnaudmiribel/streamlit-extras#179]
Upon opening [extras.streamlit.app](https://extras.streamlit.app/), I get:

<img width="1153" alt="Screenshot 2023-09-19 at 6 37 14 PM" src="https://github.com/arnaudmiribel/streamlit-extras/assets/44926683/e0cb81f1-b92d-4701-a338-09a7e1962f1c">

**Comment by arnaudmiribel** [comment]
App's back up! Thanks for telling. We are also investigating in a static fallback for our docs.
