### ISSUE TITLE
🐛 [BUG] - `st.experimental_memo is deprecated` error on streamlit-extras home page

### ISSUE THREAD

**Issue by Rjchauhan18** [arnaudmiribel/streamlit-extras#190]
### Description

- `st.experimental_memo is deprecated` error on [streamlit-extras](https://extras.streamlit.app/) home page

![image](https://github.com/arnaudmiribel/streamlit-extras/assets/113838908/10d7e8ce-b641-4350-bd80-cad585aaee47)

### Reproduction steps

```bash
1. Go to https://extras.streamlit.app/
2. See error
```

### Screenshots

```bash
![image](https://github.com/arnaudmiribel/streamlit-extras/assets/113838908/10d7e8ce-b641-4350-bd80-cad585aaee47)
```

### Version of streamlit

1.27.2

### Version of streamlit-extras

0.3.4

**Comment by arnaudmiribel** [comment]
Hey @Rjchauhan18, thanks a ton for flagging this! I think the issue came from a dependency (`streamlit-faker`). 
Published a [new release](https://github.com/arnaudmiribel/streamlit-faker/releases/tag/v0.0.3) there. Feels to me like this is fixed now, please let me know if not!
