### ISSUE TITLE
🐛 [BUG] - Metric Cards Show as default Streamlit Metric with Streamlit 1.28.0

### ISSUE THREAD

**Issue by BenseddikM** [arnaudmiribel/streamlit-extras#196]
### Description

After upgrading to Streamlit version 1.28.0, users have reported experiencing visual anomalies with the metric cards on their dashboards. The issues pertain primarily to the appearance of the metric cards, which are now showing up as default Streamlit metrics, deviating from the customized or expected visual settings.

Key Issues:

Color Mismatch: The colors of the metric cards do not render as anticipated. Users have specified colors for various components of the metric cards, but the upgrade seems to have overridden these settings, leading to a mismatch.

Background Appearance: The background of the metric cards is also affected. Instead of showing the designated background color or design, it defaults to the standard Streamlit background, disregarding any customizations made.

### Reproduction steps

```bash
1. Use latest streamlit release 1.28.0
2. Use metric cards with custom colors
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Version of streamlit

1.28.0

### Version of streamlit-extras

Latest

**Comment by arnaudmiribel** [comment]
Hey @BenseddikM! Thanks for filing this. William is investigating a fix here #197

**Comment by willhuang1997** [comment]
Just commenting here that this should be closed as my fix is merged to main. I guess you could also close it later until the release happens for streamlit-extras

**Comment by arnaudmiribel** [comment]
New version released! Should work now!
