### ISSUE TITLE
🐛 [BUG] - Streamlit 1.29.0 breaks row vertical align options

### ISSUE THREAD

**Issue by windischbauer** [arnaudmiribel/streamlit-extras#201]
### Description

Upon upgrading to streamlit 1.29.0 the vertical align options of row are no longer working.

### Reproduction steps

```bash
1. Upgrade to 1.29.0
2. Add items to a row
3. Set vertical_align='bottom'
4. Items are aligned at the top and the vertical_align options don't work anymore.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Version of streamlit

1.29.0

### Version of streamlit-extras

0.3.4

**Comment by arnaudmiribel** [comment]
Hey @windischbauer, thanks for calling this out! 

@LukasMasuch might know best how to diagnose and fix this. 😃
