### ISSUE TITLE
Edit add_logo module with also text for multipages app

### ISSUE THREAD

**Issue by davins90** [arnaudmiribel/streamlit-extras#204]
### Description

Hi guys,

I don't know if this can be helpful, but I've edited the function "add_logo" for the multi-page app, to add also a sort of "title" and "subtitle" under or above the logo, over the list of pages. Can this be a good enhancement? do I have to make a pull request? I'll link the code shortly.
Below is a preview:

![image](https://github.com/arnaudmiribel/streamlit-extras/assets/31472994/6cf2c643-89fc-48b3-acc8-ad62765c3eb9)

Thanks!

**Comment by arnaudmiribel** [comment]
Hey @davins90 

This sure sounds like a good idea! Thanks for submitting it. Please go ahead and submit a PR. 

You might want to keep in mind that it's better for changes to be retro-compatible, meaning your update to the extra should not break apps for folks that use it already and then upgrade streamlit-extras. 

For instance, if you were to add a "text" argument to the function, then it should be defaulted to something that results in the current extra. For example, text=False or text="". Hope that's clear. Give it a try!

Best
