### ISSUE TITLE
✨ [IDEA] - Stateful chat support for expanders, buttons, etc.

### ISSUE THREAD

**Issue by Vlassie** [arnaudmiribel/streamlit-extras#206]
### Description

I would love to be able to add expanders, buttons or other interactable elements to stateful chat. This could, for example, make answers from a chatbot more customizable. One example would be the ability for a RAG application to return its sources in an expander, such that the sources aren't simply added to the answer text.

**Comment by arnaudmiribel** [comment]
Hey @Vlassie, have you checked out the native [st.chat_input and st.chat_message](https://docs.streamlit.io/library/api-reference/chat)? That should work well with them!
