### ISSUE TITLE
Styleable Container - custom font

### ISSUE THREAD

**Issue by iuiu34** [arnaudmiribel/streamlit-extras#210]
### Description

Hi, 
is it possible to customize the font of widget with `stylable_container`?

code below doesn't work

```py
    with stylable_container(
            key="comic_sans_button",
            css_styles="""
             button {
                 font-family: 'Comic Sans MS', cursive, sans-serif;
             }
             """,
    ):
        st.button("Comic Sans button")
```

**Comment by arnaudmiribel** [comment]
Hey @iuiu34, 

It is! But you need to adjust the CSS path accordingly. Instead of pointing on the button itself, you need to go and point on the button's text, which is a few elements below (namely `> div > p`). Here's the updated code:

```python
import streamlit as st
from streamlit_extras.stylable_container import stylable_container

with stylable_container(
        key="comic_sans_button",
        css_styles="""
         button {
            background-color: green;
            color: white;
            border-radius: 5px;
         }

         button > div > p {
             font-family: "Comic Sans MS", "Comic Sans", cursive;
         }
         """,
):
    st.button("Comic Sans button")
```

Demo:
<img width="894" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/7164864/19a80f6a-037f-40b0-baf6-84503ebe4ae2">

**Comment by arnaudmiribel** [comment]
Btw @LukasMasuch is there a cleaner way to do this? I figured if I now added buttons before/after, while they wouldn't get the background applied, they would still use the font family. Is there a way for the font family to be only applied to the container?

<img width="905" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/7164864/593dacae-0812-4d94-b6e8-40aa8c21aaec">

**Comment by LukasMasuch** [comment]
@arnaudmiribel It should work if you add these styles in separate entries in a list, e.g.:

```python
import streamlit as st
from streamlit_extras.stylable_container import stylable_container

with stylable_container(
        key="comic_sans_button",
        css_styles=["""
         button {
            background-color: green;
            color: white;
            border-radius: 5px;
         }
         """,
         """
         button > div > p {
             font-family: "Comic Sans MS", "Comic Sans", cursive;
         }
         """
         ],
):
    st.button("Comic Sans button")

st.button("Other button")
```

<img width="700" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/2852129/94037301-2803-4f4b-b4a4-485b2298fdb0">

_btw. nice usage of the playground :)_
