### ISSUE TITLE
"add_vertical_space" is not accessed

### ISSUE THREAD

**Issue by iMoHd8** [arnaudmiribel/streamlit-extras#215]
### Description

I can't access to "add_vertical_space" and it is not shown between the methods that I can use.

![Desktop Screenshot 2024 02 01 - 15 10 33 10](https://github.com/arnaudmiribel/streamlit-extras/assets/60142199/4e071f6b-f5f4-4599-8c1f-0be488f0f875)

![Desktop Screenshot 2024 02 01 - 15 12 45 36](https://github.com/arnaudmiribel/streamlit-extras/assets/60142199/dd6c9dba-c668-4aee-b45c-87a3b331decf)

**Comment by arnaudmiribel** [comment]
Hey @iMoHd8, I can't reproduce this using `0.3.6` - what version are you using? Can you effectively use the command even if not suggested by your IDE?
