### ISSUE TITLE
st.experimental_rerun() will e removed soon and is used in stateful_button

### ISSUE THREAD

**Issue by ylaxor** [arnaudmiribel/streamlit-extras#218]
### Description

I want to keep using streamlit_extras in my application. I'm particularly interested by the stateful button widget, but it seems that it - still - uses st.experimental_rerun(). Using it raises the following warning: `st.experimental_rerun` will be removed after 2024-04-01. Would it be possible to update that line of code and put st.rerun() instead in a newer pip-installable package ? Thanks in advance.

**Comment by arnaudmiribel** [comment]
Closing this after @r-moret fixed in https://github.com/arnaudmiribel/streamlit-extras/commit/3b411d7a6bbd5cf1cbbecd8f88e4067eb76f69e3
