### ISSUE TITLE
🐛 [BUG] - Hardcoded main script path in switch_page_button extra

### ISSUE THREAD

**Issue by ivaniliash** [arnaudmiribel/streamlit-extras#220]
### Description

The main script path is hardcoded in `switch_page_button/__init__.py`
<img width="677" alt="Screenshot 2024-02-21 at 14 18 08" src="https://github.com/arnaudmiribel/streamlit-extras/assets/33152751/2bc0e22a-b3d8-4a6c-a4fe-fb881623413b">
It will always lead to a `RerunException` if the main script is renamed. Page switching still works, however the expection raising can lead to problems in error handling. For example it will not work if the `switch_page` method is part of a try/except block.

### Reproduction steps

```bash
1. Rename script
2. wrap switch_page in try/except block
3. Press switch page button
4. Nothing will happen
```

### Version of streamlit

1.30.0

### Version of streamlit-extras

0.4.0

**Comment by arnaudmiribel** [comment]
Thanks @ivaniliash - would adding a `main_module_filename: str = "streamlit_app.py"` as a parameter to the `switch_page` function solve your issue?

**Comment by ivaniliash** [comment]
@arnaudmiribel I simply replaced line 22 with `pages = get_pages(os.path.basename(__main__.__file__))`. Should work if its always the main script we are looking for.

**Comment by arnaudmiribel** [comment]
Closing this as `switch_page` is now a [native command](https://docs.streamlit.io/develop/api-reference/navigation/st.switch_page) in Streamlit!
