### ISSUE TITLE
New release on PyPI?

### ISSUE THREAD

**Issue by msabramo** [arnaudmiribel/streamlit-extras#224]
### Description

I was wanting to use the new Bottom container but it doesn't seem to be in the latest version on PyPI (0.4.0).

I wondered if perhaps it was time for a new release?

https://github.com/arnaudmiribel/streamlit-extras/compare/v0.4.0...main

**Comment by arnaudmiribel** [comment]
Here you go @msabramo https://github.com/arnaudmiribel/streamlit-extras/releases/tag/v0.4.1

**Comment by msabramo** [comment]
Thanks! 🚀

**Comment by msabramo** [comment]
I didn’t see a release on PyPI? Did that not happen yet?

**Comment by msabramo** [comment]
No worries! Thanks again, Arnaud!
