### ISSUE TITLE
🐛 [BUG] - add_logo not working with st_pages package

### ISSUE THREAD

**Issue by NanisTe** [arnaudmiribel/streamlit-extras#229]
### Description

The add_logo function does not work with the st_pages package. The logo overlaps the multipage menu items.

### Reproduction steps

```bash
1. add a pages.toml
2. run st_page.show_pages_from_config(".streamlit/pages.toml")
3. add_logo("app_logo_168x168.png",170)
4. logo overlaps the page items in sidebar.

st-annotated-text           4.0.1
st-pages                    0.4.5
st-star-rating              0.0.6
stack-data                  0.6.3
streamlit                   1.35.0
streamlit-aggrid            0.3.4.post3
streamlit-camera-input-live 0.2.0
streamlit-card              1.0.2
streamlit-embedcode         0.1.2
streamlit-extras            0.3.6
streamlit-faker             0.0.3
streamlit-feedback          0.1.3
streamlit-image-coordinates 0.1.6
streamlit-javascript        0.1.5
streamlit-keyup             0.2.4
streamlit-toggle-switch     1.0.2
streamlit-vertical-slider   2.5.5
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Version of streamlit

1.35

### Version of streamlit-extras

0.3.6

**Comment by arnaudmiribel** [comment]
Hey @NanisTe, thanks for flagging! We're working with @blackary to revamp a bit st_pages, which should solve this issue. Will keep you posted! Meanwhile, you can have a look at the latest [st.page_link](https://docs.streamlit.io/develop/api-reference/widgets/st.page_link) to craft your own navigation manually in Streamlit, in which case you can also add st.image above the navigation there.

**Comment by NanisTe** [comment]
I used Python 3.9.19 btw

**Comment by arnaudmiribel** [comment]
Btw @NanisTe have you seen the latest streamlit release? There's now a native [st.logo](https://docs.streamlit.io/develop/api-reference/media/st.logo) :-) So this extra is a bit deprecated / useless now. We keep being deprecated by streamlit... which is great.

**Comment by arnaudmiribel** [comment]
Closing in favour of st.logo
