### ISSUE TITLE
Separate gallery from package

### ISSUE THREAD

**Issue by blackary** [arnaudmiribel/streamlit-extras#23]
Could have two folders, one for actual extras, one for the gallery app (and the gallery app could have a separate, tighter set of dependencies).

That way we can have much looser requirements on the package itself.

**Comment by arnaudmiribel** [comment]
```
README.md
LICENSE
pyproject.toml
poetry.lock
.flake8
.gitignore
.pre-commit-config.yml
src/streamlit_extras/
app/streamlit_app.py
app/streamlit_patches.py
app/requirements.txt 
tests/
```
