### ISSUE TITLE
🐛 [BUG] - bottom() doesn't respect sidebar

### ISSUE THREAD

**Issue by Ginner** [arnaudmiribel/streamlit-extras#232]
### Description

I'd like to add text to the bottom of the sidebar. However, putting a bottom container in the sidebar, moves the container to the bottom of the content window. 

### Reproduction steps

1. Create the following app:
```python
import streamlit as st
from streamlit_extras.bottom_container import bottom

st.write("Hello World")

with st.sidebar:
    st.write("This is a sidebar")
    with bottom():
        st.write("This should be in the bottom of the sidebar.")
```
2. run the app

### Version of streamlit

1.36.0

### Version of streamlit-extras

0.4.3

**Comment by arnaudmiribel** [comment]
Ah, good point, I can reproduce this. Will let @LukasMasuch respond if that was meant to work - if not, worth stressing that it doesn't work in the docs.

**Comment by LukasMasuch** [comment]
@Ginner The bottom contains always refers to a root container at the bottom of the main content area. This is similar to `st.sidebar`. So, it doesn't really matter where you call it.

**Comment by Ginner** [comment]
Okay, so to understand correctly, it is the intended behavior? If so, I'd agree with [arnaudmiribel](https://github.com/arnaudmiribel) in specifying it in the docs.

I'd find the functionality of being able to use it in the sidebar useful.
