### ISSUE TITLE
image_selector, no "key" argument

### ISSUE THREAD

**Issue by alon-sht** [arnaudmiribel/streamlit-extras#244]
### Description

Please add "key" argument to image_selector so we can add multiple image_selectors

**Comment by arnaudmiribel** [comment]
Hey @alon-sht, thank you for the issue. That is right, I did not test with multiple of them 😇  Will add this.

Btw, curious what you're using this for?

**Comment by alon-sht** [comment]
Thanks, i have an app where i do biological assay quantification from images (e.g. western blots)
The users select regions of interest, and it quantifies the intensity of the signal in the ROIs

**Comment by arnaudmiribel** [comment]
That sounds cool @alon-sht, let me know if you have a public facing app and want to share more with the community at https://discuss.streamlit.io!
