### ISSUE TITLE
🐛 [BUG] - Metrics display incorrect when windows in dark mode

### ISSUE THREAD

**Issue by rubgithub** [arnaudmiribel/streamlit-extras#252]
### Description

Metrics display incorrect when windows in dark mode

### Reproduction steps

```bash
1. Set windows to dark mode
2. https://arnaudmiribel.github.io/streamlit-extras/extras/metric_cards/
```

### Screenshots

```bash
https://snipboard.io/QgLhEu.jpg
```

### Logs

```bash
No log
```

### Version of streamlit

1.37.1

### Version of streamlit-extras

0.4.7

**Comment by rubgithub** [comment]
![image](https://github.com/user-attachments/assets/fe9eef16-4f02-4b16-b9e7-0a78a018a9b2)

**Comment by arnaudmiribel** [comment]
Hey @rubgithub, thanks for calling this out! Was already raised in #227.

Here's a fix:

```python
from streamlit_extras.theme import st_theme
theme = st_theme()

# When dark mode, convert background and border to be dark
if theme.get("base") == "dark":
    background_color = "#1B1C24"
    border_color = "#292D34"
```

which will have the metrics look like that, wdyt?

![CleanShot 2024-10-31 at 10 53 09@2x](https://github.com/user-attachments/assets/909fb6c3-816c-4ddd-be29-6052ea4d8990)
