### ISSUE TITLE
Gallery preview while developing

### ISSUE THREAD

**Issue by arnaudmiribel** [arnaudmiribel/streamlit-extras#29]
As we implemented #24, it is now not straightforward to test the gallery while adding a new extra! Let's tackle that.

**Comment by blackary** [comment]
Because of the dependencies being different?

**Comment by arnaudmiribel** [comment]
> Because of the dependencies being different?

Hmm because the app uses the built package and not the current directory anymore? So if there's a new extra being developed in the directory, it won't be featured

**Comment by arnaudmiribel** [comment]
I tried `poetry run streamlit run gallery/streamlit_app.py` but since poetry allows latest Streamlit the patching fails and the app, too. Indeed, gallery/streamlit_app.py should be run only with streamlit==1.12.2 (as specified in its gallery/requirements.txt)

**Comment by blackary** [comment]
Ah, yeah -- that is a problem. I try and think of a good solution.

**Comment by arnaudmiribel** [comment]
Fixed by #32
