### ISSUE TITLE
Unable to install under 3.10 Python

### ISSUE THREAD

**Issue by talentai** [arnaudmiribel/streamlit-extras#48]
Hi All, fantastic addons! I try them on Streamlit Cloud, but unable to install on local Python 3.10, seems like 3.9 works. Is there a solution? Thanks! 

![image](https://user-images.githubusercontent.com/104866043/196087253-dc33bb15-425b-45df-a20c-dcd5279f06a7.png)

**Comment by arnaudmiribel** [comment]
Hey @talentai! Thanks for your support! 

@blackary just shipped a release that should fix that (see https://github.com/arnaudmiribel/streamlit-extras/pull/49#event-7612582707), can you make sure that your app uses the latest version `streamlit-extras==0.1.5` and see if that resolves the issue?

**Comment by blackary** [comment]
@talentai This is related to this issue https://github.com/tvst/htbuilder/pull/3 with one of our dependencies, which will hopefully be resolved soon

**Comment by blackary** [comment]
@talentai Could you try installing streamlit-extras 0.2.0 and see if that resolves your issue?

**Comment by arnaudmiribel** [comment]
Closing after inactivity
