### ISSUE TITLE
Passing args in the switch_page function

### ISSUE THREAD

**Issue by LorenzoVela** [arnaudmiribel/streamlit-extras#71]
Hi all,

Is there a way to pass an argument with the switch_page function?
Given the fact that the function can't be inserted in the "on-click" parameter of a button it would be quite useful to have the possibility to pass some arguments. Could be this a possible ER? Or is there already a way to perform this action? 

Thank you
Regards,
Lorenzo

**Comment by blackary** [comment]
Hi @LorenzoVela,

Unfortunately, callbacks don't seem to work for this function, but you should be able to use a button to trigger this function in this way:

```python
import streamlit as st
from streamlit_extras.switch_page_button import switch_page

if st.button("Click me"):
    switch_page("page1")
````
