### ISSUE TITLE
"Dataframe explorer UI" not working

### ISSUE THREAD

**Issue by chincherpa** [arnaudmiribel/streamlit-extras#93]
Hi,

when I check the checkbox "I want to explore", the site reruns but nothing more happens.

Reproducible even on your demo page:
https://extras.streamlit.app/Dataframe%20explorer%20UI

I am sure version 0.2.2 worked fine.

**Comment by arnaudmiribel** [comment]
Good point! Fixing this in next release. Actually removing the "I want to explore" checkbox, this should not be there in the first place.

**Comment by arnaudmiribel** [comment]
@chincherpa can you confirm that `pip install streamlit-extras --upgrade` fixed that? :-)

**Comment by chincherpa** [comment]
Yes, I can confirm! Works as expected
